// flow-typed signature: 35901fe065512439d963ed31828200d1
// flow-typed version: <<STUB>>/eslint-plugin-classes_v^0.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-classes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-classes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-classes/lib/rules/constructor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/lib/rules/name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/lib/rules/space' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/lib/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/lib/rules/super' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/tests/rules/constructor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/tests/rules/name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/tests/rules/space' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/tests/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-classes/tests/rules/super' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-classes/index' {
  declare module.exports: $Exports<'eslint-plugin-classes'>;
}
declare module 'eslint-plugin-classes/index.js' {
  declare module.exports: $Exports<'eslint-plugin-classes'>;
}
declare module 'eslint-plugin-classes/lib/rules/constructor.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/lib/rules/constructor'>;
}
declare module 'eslint-plugin-classes/lib/rules/name.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/lib/rules/name'>;
}
declare module 'eslint-plugin-classes/lib/rules/space.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/lib/rules/space'>;
}
declare module 'eslint-plugin-classes/lib/rules/style.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/lib/rules/style'>;
}
declare module 'eslint-plugin-classes/lib/rules/super.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/lib/rules/super'>;
}
declare module 'eslint-plugin-classes/tests/rules/constructor.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/tests/rules/constructor'>;
}
declare module 'eslint-plugin-classes/tests/rules/name.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/tests/rules/name'>;
}
declare module 'eslint-plugin-classes/tests/rules/space.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/tests/rules/space'>;
}
declare module 'eslint-plugin-classes/tests/rules/style.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/tests/rules/style'>;
}
declare module 'eslint-plugin-classes/tests/rules/super.js' {
  declare module.exports: $Exports<'eslint-plugin-classes/tests/rules/super'>;
}
