// flow-typed signature: 5e372faf77e6d5605f14e1153a461b88
// flow-typed version: <<STUB>>/eslint-plugin-ideal_v^0.1.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-ideal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-ideal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-ideal/lib/rules/no-tabs-in-file' {
  declare module.exports: any;
}

declare module 'eslint-plugin-ideal/lib/rules/vars-on-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-ideal/lib/rules/vars-with-default' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-ideal/index' {
  declare module.exports: $Exports<'eslint-plugin-ideal'>;
}
declare module 'eslint-plugin-ideal/index.js' {
  declare module.exports: $Exports<'eslint-plugin-ideal'>;
}
declare module 'eslint-plugin-ideal/lib/rules/no-tabs-in-file.js' {
  declare module.exports: $Exports<'eslint-plugin-ideal/lib/rules/no-tabs-in-file'>;
}
declare module 'eslint-plugin-ideal/lib/rules/vars-on-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-ideal/lib/rules/vars-on-newline'>;
}
declare module 'eslint-plugin-ideal/lib/rules/vars-with-default.js' {
  declare module.exports: $Exports<'eslint-plugin-ideal/lib/rules/vars-with-default'>;
}
