// flow-typed signature: b03e642d4648648c1ecca9d5635edc32
// flow-typed version: <<STUB>>/eslint-plugin-promiseparams_v^1.0.8/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-promiseparams'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-promiseparams' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-promiseparams/promiseparams' {
  declare module.exports: any;
}

declare module 'eslint-plugin-promiseparams/test/promiseparams.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-promiseparams/index' {
  declare module.exports: $Exports<'eslint-plugin-promiseparams'>;
}
declare module 'eslint-plugin-promiseparams/index.js' {
  declare module.exports: $Exports<'eslint-plugin-promiseparams'>;
}
declare module 'eslint-plugin-promiseparams/promiseparams.js' {
  declare module.exports: $Exports<'eslint-plugin-promiseparams/promiseparams'>;
}
declare module 'eslint-plugin-promiseparams/test/promiseparams.test.js' {
  declare module.exports: $Exports<'eslint-plugin-promiseparams/test/promiseparams.test'>;
}
