// flow-typed signature: fca05ff4d3f4aa0782cfb45cb05f8f77
// flow-typed version: <<STUB>>/public-ip_v^2.3.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'public-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'public-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'public-ip/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'public-ip/browser.js' {
  declare module.exports: $Exports<'public-ip/browser'>;
}
declare module 'public-ip/index' {
  declare module.exports: $Exports<'public-ip'>;
}
declare module 'public-ip/index.js' {
  declare module.exports: $Exports<'public-ip'>;
}
